### ISSUE TITLE
IDE for this project ?

### ISSUE THREAD

**Issue by bhausahebkhamat** [arashpayan/pbdbbuilder#1]
Amazing work @arashpayan ,
which IDE is used for this project. Hope this project is for Jet DB creation. Please let us know how you build this project and which IDE, any documentation.

Kind Regards :-)

**Comment by arashpayan** [comment]
Hi @bhausahebkhamat. The code is for an Xcode project. You can create a compilation of prayers with it, and then it saves the compilation to a SQLite database file with a schema I designed. I made a video a couple years that goes over how to use the app:
https://ara.sh/PrayerBook/pbdb_overview.mov
